CREATE DATABASE CHAEA;

USE CHAEA;

CREATE TABLE Aprendizaje(id INT AUTO_INCREMENT, texto TEXT, PRIMARY KEY (id));
CREATE TABLE Grupo(id INT AUTO_INCREMENT, texto TEXT, PRIMARY KEY (id));
CREATE TABLE Alumno(id INT AUTO_INCREMENT, grupo INT, PRIMARY KEY (id), FOREIGN KEY (grupo) REFERENCES Grupo(id));
CREATE TABLE Pregunta(id INT AUTO_INCREMENT, texto TEXT, aprendizaje INT, PRIMARY KEY (id), FOREIGN KEY (aprendizaje) REFERENCES Aprendizaje(id));
CREATE TABLE Cuestionario(id INT AUTO_INCREMENT, alumno INT, fecha DATE, cantActivo INT, cantReflexivo INT, cantTeorico INT, cantPragmatico INT, PRIMARY KEY (id), FOREIGN KEY (alumno) REFERENCES Alumno(id));

INSERT INTO `Aprendizaje`(`id`, `texto`) VALUES (1,"ACTIVO");
INSERT INTO `Aprendizaje`(`id`, `texto`) VALUES (2,"REFLEXIVO");
INSERT INTO `Aprendizaje`(`id`, `texto`) VALUES (3,"TEORICO");
INSERT INTO `Aprendizaje`(`id`, `texto`) VALUES (4,"PRAGMATICO");

INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (3,"3. Muchas veces actúo sin mirar las consecuencias.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (5,"5. Creo que los formalismos coartan y limitan la actuación libre de las personas.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (7,"7. Pienso que el actuar intuitivamente puede ser siempre tan válido como actuar reflexivamente.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (9,"9. Procuro estar al tanto de lo que ocurre aquí y ahora.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (13,"13. Prefiero las ideas originales y novedosas aunque no sean prácticas.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (20,"20. Me entusiasmo con el reto de hacer algo nuevo y diferente.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (26,"26. Me siento a gusto con personas espontáneas y divertidas.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (27,"27. La mayoría de las veces expreso abiertamente cómo me siento.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (35,"35. Me gusta afrontar la vida espontáneamente y no tener que planificar todo previamente.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (37,"37. Me siento incómodo/a con las personas calladas y demasiado analíticas.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (41,"41. Es mejor gozar del momento presente que deleitarse pensando en el pasado o en el futuro.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (43,"43. Aporto ideas nuevas y espontáneas en los grupos de discusión.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (46,"46. Creo que es preciso saltarse las normas muchas más veces que cumplirlas.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (48,"48. En conjunto hablo más que escucho.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (51,"51. Me gusta buscar nuevas experiencias.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (61,"61. Cuando algo va mal, le quito importancia y trato de hacerlo mejor.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (67,"67. Me resulta incómodo tener que planificar y prever las cosas.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (74,"74. Con frecuencia soy una de las personas que más anima las fiestas.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (75,"75. Me aburro enseguida con el trabajo metódico y minucioso.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (77,"77. Suelo dejarme llevar por mis intuiciones.",1);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (10,"10. Disfruto cuando tengo tiempo para preparar mi trabajo y realizarlo a conciencia.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (16,"16. Escucho con más frecuencia que hablo.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (18,"18. Cuando poseo cualquier información, trato de interpretarla bien antes de manifestar alguna conclusión.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (19,"19. Antes de hacer algo estudio con cuidado sus ventajas e inconvenientes.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (28,"28. Me gusta analizar y dar vueltas a las cosas.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (31,"31. Soy cauteloso/a a la hora de sacar conclusiones.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (32,"32. Prefiero contar con el mayor número de fuentes de información. Cuantos más datos reúna para reflexionar, mejor.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (34,"34. Prefiero oír las opiniones de los demás antes de exponer la mía.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (36,"36. En las discusiones me gusta observar cómo actúan los demás participantes.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (39,"39. Me agobio si me obligan a acelerar mucho el trabajo para cumplir un plazo.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (42,"42. Me molestan las personas que siempre desean apresurar las cosas.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (44,"44. Pienso que son más consistentes las decisiones fundamentadas en un minucioso análisis que las basadas en la intuición.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (49,"49. Prefiero distanciarme de los hechos y observarlos desde otras perspectivas.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (55,"55. Prefiero discutir cuestiones concretas y no perder el tiempo con pláticas superficiales.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (58,"58. Hago varios borradores antes de la redacción definitiva de un trabajo.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (63,"63. Me gusta sopesar diversas alternativas antes de tomar una decisión.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (65,"65. En los debates y discusiones prefiero desempeñar un papel secundario antes que ser el/la líder o el/la que más participa.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (69,"69. Suelo reflexionar sobre los asuntos y problemas.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (70,"70. El trabajar a conciencia me llena de satisfacción y orgullo.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (79,"79. Con frecuencia me interesa averiguar lo que piensa la gente.",2);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (2,"2. Estoy seguro/a de lo que es bueno y lo que es malo, lo que está bien y lo que está mal.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (4,"4. Normalmente trato de resolver los problemas metódicamente y paso a paso.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (6,"6. Me interesa saber cuáles son los sistemas de valores de los demás y con qué criterios actúan.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (11,"11. Estoy a gusto siguiendo un orden en las comidas, en el estudio, haciendo ejercicio regularmente.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (15,"15. Normalmente encajo bien con personas reflexivas, y me cuesta sintonizar con personas demasiado espontáneas, imprevisibles.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (17,"17. Prefiero las cosas estructuradas a las desordenadas.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (21,"21. Casi siempre procuro ser coherente con mis criterios y sistemas de valores. Tengo principios y los sigo.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (23,"23. Me disgusta implicarme afectivamente en el ambiente de la escuela. Prefiero mantener relaciones distantes.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (25,"25. Me cuesta ser creativo/a, romper estructuras.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (29,"29. Me molesta que la gente no se tome en serio las cosas.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (33,"33. Tiendo a ser perfeccionista.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (45,"45. Detecto frecuentemente la inconsistencia y puntos débiles en las argumentaciones de los demás.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (50,"50. Estoy convencido/a que debe imponerse la lógica y el razonamiento.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (54,"54. Siempre trato de conseguir conclusiones e ideas claras.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (60,"60. Observo que, con frecuencia, soy uno/a de los/as más objetivos/as y desapasionados/as en las discusiones.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (64,"64. Con frecuencia miro hacia delante para prever el futuro.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (66,"66. Me molestan las personas que no actúan con lógica.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (71,"71. Ante los acontecimientos trato de descubrir los principios y teorías en que se basan.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (78,"78. Si trabajo en grupo procuro que se siga un método y un orden.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (80,"80. Esquivo los temas subjetivos, ambiguos y poco claros.",3);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (1,"1. Tengo fama de decir lo que pienso claramente y sin rodeos.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (8,"8. Creo que lo más importante es que las cosas funcionen.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (12,"12. Cuando escucho una nueva idea enseguida comienzo a pensar cómo ponerla en práctica.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (14,"14. Admito y me ajusto a las normas sólo si me sirven para lograr mis objetivos.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (22,"22. Cuando hay una discusión no me gusta ir con rodeos.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (24,"24. Me gustan más las personas realistas y concretas que las teóricas.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (30,"30. Me atrae experimentar y practicar las últimas técnicas y novedades.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (38,"38. Juzgo con frecuencia las ideas de los demás por su valor práctico.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (40,"40. En las reuniones apoyo las ideas prácticas y realistas.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (47,"47. A menudo caigo en la cuenta de otras formas mejores y más prácticas de hacer las cosas.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (52,"52. Me gusta experimentar y aplicar las cosas.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (53,"53. Pienso que debemos llegar pronto al grano, al meollo de los temas.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (56,"56. Me impaciento cuando me dan explicaciones irrelevantes e incoherentes.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (57,"57. Compruebo antes si las cosas funcionan realmente.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (59,"59. Soy consciente de que en las discusiones ayudo a mantener a los demás centrados en el tema, evitando divagaciones.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (62,"62. Rechazo ideas originales y espontáneas si no las veo prácticas.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (68,"68. Creo que el fin justifica los medios en muchos casos.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (72,"72. Con tal de conseguir el objetivo que pretendo soy capaz de herir sentimientos ajenos.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (73,"73. No me importa hacer todo lo necesario para que sea efectivo mi trabajo.",4);
INSERT INTO `Pregunta`(`id`, `texto`, `aprendizaje`) VALUES (76,"76. La gente con frecuencia cree que soy poco sensible a sus sentimientos.",4);